Week1
CUB-Computational-Tools/2020-ps-vaga3461 pull request #1
Opened 2020-09-01 20:56 UTC by vaga3461

Pull request for week1 problem set; needs peer reviews

2020-09-01 21:01 UTC, vaga3461 commented
Binder link for reviewers: <a href='https://mybinder.org/v2/gh/CUB-Computational-Tools/assignment_problem_set/binder-python?urlpath=git-pull?repo=https%3A%2F%2Fgithub.com%2FCUB-Computational-Tools%2Fassignment_problem_set%26branch%3Dweek1%26urlpath%3Dlab'><img src='https://img.shields.io/badge/launch%20draft-Py+Jupyter%20Lab-red.svg'/></a>

2020-09-01 22:18 UTC, KevRozmiarek requested changes
Overall, great work! I feel like I should personally provide more background on mine having read this.....

2020-09-01 22:18 UTC, KevRozmiarek commented on week1.ipynb
> +    "where $F$ is a force and $d$ is the displacement, or the distance over which the force acts. We can see from this equation that work is zero if the displacement of an object is zero, $\\textit{w
The textit looks awkward in the complied doc

2020-09-01 22:18 UTC, KevRozmiarek commented on week1.ipynb
> +    "Work is a force acting over a distance. Specifically, it is calculated from the displacement of an object parallel to the force acting on it. In this lesson we will only condsider forces acting
It is just displacement. The word parallel is confusing here.

2020-09-01 22:18 UTC, KevRozmiarek commented on week1.ipynb
> +    "Let's imagine an apple falling to the ground from a height of 10 feet. Its mass is 100 g. We will calculate how much work was done on the apple, and in the question below you will find the chang
"stationary"

2020-09-01 22:18 UTC, KevRozmiarek commented on week1.ipynb
> +    "- A box sitting stationary on a table\n",
I think you might have to explain a reference frame more explicitly to ask this question. I imply it in the next one though!

2020-09-02 03:09 UTC, splazatorres reviewed
Hi. For some reason, the comments (I made) on the ReviewNB page are not showing up here. let me know if you can access them or if you don't see them. Also, great work! I really loved how well explained, clear, and well-thought-out the notebook was!

2020-09-02 03:18 UTC, vaga3461 commented
Thanks, Stephanie! Yes, I was able to see your comments on ReviewNB. Not sure why they showed up in different places, but I found them all :)

2020-09-02 03:35 UTC, splazatorres commented
Awesome. Also, I couldn't access your notebook in binder. Seb let me know it might be because you still have the original template name in the README.md file (the assignment-problem-set instead of your repo name).

2020-09-02 03:51 UTC, vaga3461 commented
Reviewers: please use this link for binder! https://mybinder.org/v2/gh/CUB-Computational-Tools/2020-ps-vaga3461/binder-python?urlpath=git-pull?repo=https%3A%2F%2Fgithub.com%2FCUB-Computational-Tools%2F2020-ps-vaga3461%26branch%3Dweek1%26urlpath%3Dlab

2020-09-03 03:12 UTC, vaga3461 commented
About to merge - wish me luck

2020-09-03 03:13 UTC, merged